[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    #me-no-dev/ESPAsyncWebServer
    me-no-dev/AsyncTCP
    ArduinoOTA

lib_extra_dirs = 
    lib

build_flags = 
    -L"${PROJECT_DIR}/lib/micro_ros_arduino/src/esp32"
    -Wl,--whole-archive
    -lmicroros
    -Wl,--no-whole-archive

#upload_protocol = espota
#upload_port = 192.168.1.169
#upload_flags = --auth=admin123